/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const TeamsLazyRouteImport = createFileRoute('/teams')()
const PlayersLazyRouteImport = createFileRoute('/players')()
const LeaguesLazyRouteImport = createFileRoute('/leagues')()
const IndexLazyRouteImport = createFileRoute('/')()

const TeamsLazyRoute = TeamsLazyRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/teams.lazy').then((d) => d.Route))
const PlayersLazyRoute = PlayersLazyRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/players.lazy').then((d) => d.Route))
const LeaguesLazyRoute = LeaguesLazyRouteImport.update({
  id: '/leagues',
  path: '/leagues',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/leagues.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/leagues': typeof LeaguesLazyRoute
  '/players': typeof PlayersLazyRoute
  '/teams': typeof TeamsLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/leagues': typeof LeaguesLazyRoute
  '/players': typeof PlayersLazyRoute
  '/teams': typeof TeamsLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/leagues': typeof LeaguesLazyRoute
  '/players': typeof PlayersLazyRoute
  '/teams': typeof TeamsLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/leagues' | '/players' | '/teams'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/leagues' | '/players' | '/teams'
  id: '__root__' | '/' | '/leagues' | '/players' | '/teams'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  LeaguesLazyRoute: typeof LeaguesLazyRoute
  PlayersLazyRoute: typeof PlayersLazyRoute
  TeamsLazyRoute: typeof TeamsLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues': {
      id: '/leagues'
      path: '/leagues'
      fullPath: '/leagues'
      preLoaderRoute: typeof LeaguesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  LeaguesLazyRoute: LeaguesLazyRoute,
  PlayersLazyRoute: PlayersLazyRoute,
  TeamsLazyRoute: TeamsLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
